/*---------------------------------------------------------------------
-- This file TablesForLab9.sql creates all necessary objects for Lab9 
	(files for Lab8 are also created here as they are used for 
	creating tables of Lab9)
-----------------------------------------------------------------------
*/
-- SET ECHO OFF
DROP TABLE CUSTOMERS_COPY;
DROP TABLE ORDERS_COPY;
drop TABLE  T_ORDER_DATE;
DROP TABLE T_DATE;
DROP SEQUENCE SEQ_ID_DATE;
DROP TABLE T_SALESMAN;
DROP TABLE F_ORDERS;
DROP TABLE D_CUSTOMERS;
DROP TABLE D_TIME;
DROP TABLE D_ORDERS;
DROP TABLE D_SALESMAN;
DROP SEQUENCE SEQ_F_ORDERS;


-- SET ECHO ON
-- CREATE CUSTOMERS_COPY
CREATE TABLE CUSTOMERS_COPY AS
SELECT CUSTOMER_ID, CUST_FIRST_NAME, CUST_LAST_NAME, NLS_LANGUAGE, NLS_TERRITORY,
CREDIT_LIMIT, CUST_EMAIL, ACCOUNT_MGR_ID, CUST_GEO_LOCATION, DATE_OF_BIRTH,
MARITAL_STATUS, GENDER, INCOME_LEVEL
FROM OE.CUSTOMERS;

--  CREATE ORDERS_COPY
CREATE TABLE ORDERS_COPY AS
SELECT * FROM OE.ORDERS;


--  CREATE T_ORDERS_DATE
CREATE TABLE  T_ORDER_DATE AS 
SELECT  DISTINCT TO_DATE(TO_CHAR(ORDER_DATE, 'DD-MON-YYYY')) ORDER_DATE from OE.ORDERS;

CREATE TABLE T_DATE (
ID_DATE NUMBER(5),
ORDER_DATE	DATE,
Day_No	NUMBER(1),
Day_Name	CHAR(10),
Month_NO	NUMBER(2),
Month_Name 	CHAR(10),
Quarter	NUMBER(1),
YYear		NUMBER(4),
CONSTRAINT PK_ID_DATE PRIMARY KEY (ID_DATE));

--  CREATE SEQUENCE SEQ_ID_DATE
CREATE SEQUENCE SEQ_ID_DATE START WITH 10000;

-- INSERTING DATA INTO T_DATE 
INSERT INTO T_DATE
SELECT  SEQ_ID_DATE.NEXTVAL, ORDER_DATE,
    TO_NUMBER(TO_CHAR(ORDER_DATE,'D')),
    TO_CHAR(ORDER_DATE,'Day'),
    TO_NUMBER(TO_CHAR(ORDER_DATE,'MM')),
    TO_CHAR(ORDER_DATE,'MONTH'),
    TO_NUMBER(TO_CHAR(ORDER_DATE,'Q')),
    TO_NUMBER(TO_CHAR(ORDER_DATE,'YYYY'))
FROM T_ORDER_DATE;


-- 1  CREATE TABLE T_SALESMAN

CREATE TABLE T_SALESMAN AS
SELECT Distinct (SALES_REP_ID)
FROM OE.ORDERS;

-- REPLACING NULLs WITH 999 in TABLE T_SALESMAN
UPDATE T_SALESMAN
SET SALES_REP_ID=NVL(SALES_REP_ID,999);

-- ALTER TABLE T_SALESMAN Adding SNAME COLUMN
ALTER TABLE T_SALESMAN
ADD SNAME varchar(255);

-- UPDATE NAMES in T_SALESMAN 
UPDATE T_SALESMAN
SET SNAME= 'NAME-' || SALES_REP_ID;



--2   Create 4 Dimension Tables
-- CREATE TABLE D_CUSTOMERS
create table  D_CUSTOMERS
as select CUSTOMER_ID ID_C , CUST_FIRST_NAME C_FNAME, CUST_LAST_NAME C_LNAME, GENDER ,MARITAL_STATUS TTYPE
from CUSTOMERS_COPY;
-- CREATE TABLE D_TIME
create table  D_TIME as select ID_DATE ID_T , ORDER_DATE DDATE, MONTH_NO, MONTH_NAME,QUARTER, YYEAR
from t_date;
-- CREATE TABLE D_ORDERS
create table  D_ORDERS as select ORDER_ID ID_O ,ORDER_MODE OMode, ORDER_STATUS STATUS
FROM ORDERS_COPY;
-- CREATE TABLE D_SALESMAN
create table  D_SALESMAN as select SALES_REP_ID ID_S , SNAME
FROM T_SALESMAN;

-- ADD Primary key constraints 

ALTER TABLE D_CUSTOMERS ADD CONSTRAINT PK_D_CUSTOMERS
PRIMARY KEY(ID_C);

ALTER TABLE D_ORDERS ADD CONSTRAINT PK_D_ORDERS 
PRIMARY KEY(ID_O);

ALTER TABLE D_SALESMAN ADD CONSTRAINT PK_D_SALESMAN 
PRIMARY KEY(ID_S);

ALTER TABLE D_TIME ADD CONSTRAINT PK_D_TIME 
PRIMARY KEY(ID_T);


-- CREATE Fact table F_ORDERS
CREATE TABLE F_ORDERS (
F_ORDERS_ID NUMBER(22),
ORDER_AMOUNT NUMBER(22,2),
F_ID_C	NUMBER(22),
F_ID_O	NUMBER(22),
F_ID_T	NUMBER(22),
F_ID_S 	NUMBER(22)
);

--2  ALTER TABLE F_ORDERS
ALTER TABLE F_ORDERS ADD CONSTRAINT PK_F_ORDERS_ID PRIMARY KEY (F_ORDERS_ID);


--3  ALTER TABLE F_ORDERS
ALTER TABLE F_ORDERS ADD CONSTRAINT FK_F_ORDERS_TO_CUSTOMERS
FOREIGN KEY(F_ID_C) REFERENCES D_CUSTOMERS(ID_C);

ALTER TABLE F_ORDERS ADD CONSTRAINT FK_F_ORDERS_TO_ORDERS
FOREIGN KEY(F_ID_O) REFERENCES D_ORDERS (ID_O);

ALTER TABLE F_ORDERS ADD CONSTRAINT FK_F_ORDERS_TO_SALESMAN
FOREIGN KEY(F_ID_S) REFERENCES D_SALESMAN (ID_S);

ALTER TABLE F_ORDERS ADD CONSTRAINT FK_F_ORDERS_TO_TIME
FOREIGN KEY(F_ID_T) REFERENCES D_TIME (ID_T);

--4 CREATE SEQUENCE SEQ_F_ORDERS
CREATE SEQUENCE SEQ_F_ORDERS START WITH 1;


--5  INSERT INTO F_ORDERS
INSERT INTO F_ORDERS
SELECT SEQ_F_ORDERS.NEXTVAL,
        ORDER_TOTAL,
        ID_C,
        ID_O,
        ID_T,
        ID_S
FROM   ORDERS_COPY  
LEFT JOIN   D_CUSTOMERS ON ORDERS_COPY.CUSTOMER_ID=D_CUSTOMERS.ID_C
LEFT JOIN  	D_ORDERS ON ORDERS_COPY.ORDER_ID =D_ORDERS.ID_O
LEFT JOIN   D_TIME ON TO_DATE(TO_CHAR(ORDERS_COPY.ORDER_DATE,'DD-MON-YY'))= D_TIME.DDATE 
LEFT JOIN   D_SALESMAN ON ORDERS_COPY.SALES_REP_ID =D_SALESMAN.ID_S;

